start-date-time: 2022-06-08T18:00:00Z
instance-offset-hours: 24
process-variants:
  - name: manual
    qty: 10
    tasks: 
      - New Client Onboarding Request
      - Review Documents
      - Automated Scoreboarding
      - Manual Scoreboarding
      - Update Backend Systems
      - Notification Review Request Completed
  - name: auto
    qty: 50
    tasks:
      - New Client Onboarding Request
      - Review Documents
      - Automated Scoreboarding
      - Update Backend Systems
      - Notification Review Request Completed


    
